pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}
rootProject.name = "ClassicsReaderAndroid"
include ':core'
include ':views'
include ':compose'
include ':latinreader'
include ':greekreader'
include ':latinreader:views'
include ':latinreader:compose'
include ':greekreader:views'
include ':greekreader:compose'
