import org.jetbrains.kotlin.gradle.dsl.JvmTarget

apply plugin: 'com.android.library'
apply plugin: "androidx.navigation.safeargs"
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {
    namespace("com.ericmschmidt.classicsreader")
    compileSdk(36)

    dataBinding {
        enabled = true
    }

    defaultConfig {
        minSdkVersion(23)
        targetSdkVersion(36)
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8 // Ensure this is 1.8
        targetCompatibility = JavaVersion.VERSION_1_8 // Ensure this is 1.8
    }
    buildFeatures {
        compose = true
        viewBinding = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.10"
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation 'androidx.compose.ui:ui-tooling:1.9.4'
    def nav_version = '2.9.0'
    def lifecycle_version = rootProject.extensions["ext"]["lifecycle_version"]
    implementation(fileTree(dir: 'libs', include: ['*.jar']))

    // TODO: Clean build script to remove duplicative dependencies
    implementation(platform("androidx.compose:compose-bom:2025.08.00"))
    implementation("androidx.appcompat:appcompat:1.7.1")
    implementation("androidx.activity:activity-compose:1.8.2")
    implementation("androidx.compose.foundation:foundation:1.7.0+")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.compose.material:material-ripple:1.7.0+")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material3:material3-window-size-class")
    implementation("androidx.compose.material3.adaptive:adaptive:1.2.0-alpha11")
    implementation("androidx.compose.material3.adaptive:adaptive-layout:1.2.0-alpha11")
    implementation("androidx.compose.material3.adaptive:adaptive-navigation:1.2.0-alpha11")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.core:core-ktx:1.17.0")
    implementation("androidx.datastore:datastore-preferences:1.1.7")
    implementation('androidx.legacy:legacy-support-v4:1.0.0')
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycle_version")
    implementation("androidx.navigation:navigation-fragment:$nav_version")
    implementation("androidx.navigation:navigation-ui:$nav_version")
    implementation('androidx.preference:preference-ktx:1.2.1')

    implementation('androidx.recyclerview:recyclerview:1.4.0')

    // Third-party MD viewer
    implementation('com.github.mukeshsolanki:MarkdownView-Android:1.1.1')

    debugImplementation("androidx.compose.ui:ui-test-manifest")
    debugImplementation("androidx.compose.ui:ui-tooling")

    // Test resources
    androidTestImplementation(platform("androidx.compose:compose-bom:2024.03.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation('com.android.support.test:runner:1.0.2')
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.2')
    testImplementation("junit:junit:4.13.2")
    testImplementation('com.google.truth:truth:1.4.4')
    testImplementation('org.mockito:mockito-core:5.18.0')
    testImplementation('androidx.test:core:1.6.1')
    testImplementation('org.robolectric:robolectric:4.14.1')
    testImplementation('org.powermock:powermock-api-mockito:1.7.4')
    testImplementation('org.powermock:powermock-module-junit4-rule-agent:2.0.9')
    testImplementation('org.powermock:powermock-module-junit4-rule:2.0.9')
    testImplementation('org.powermock:powermock-module-junit4:2.0.9')
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
repositories {
    mavenCentral()
}
