apply plugin: 'com.android.application'

android {
    namespace("com.ericmschmidt.greekreader")
    compileSdk(36)
    dataBinding {
        enabled = true
    }
    defaultConfig {
        applicationId("com.telpirion.greekreader")
        minSdkVersion(23)
        targetSdk(36)
        versionCode(1)
        versionName("1.0")
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation project(':core')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
