plugins {
    alias(libs.plugins.compose.compiler)
    alias libs.plugins.android.application
}

android {
    namespace="com.ericmschmidt.classicsreader.latin.compose"
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.ericmschmidt.latinreader"
        minSdk 24
        targetSdk 37
        versionCode(22)
        versionName("3.0.0")

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    kotlin {
        jvmToolchain {
            languageVersion = JavaLanguageVersion.of("24")
        }
    }
    testOptions {
        emulatorControl {
            enable = true
        }
    }
    packaging {
        resources.excludes.add("META-INF/LICENSE.md")
        resources.excludes.add("META-INF/LICENSE-notice.md")
    }
}

dependencies {
    implementation project(":core")
    implementation project(":compose")
    implementation project(":latinreader")
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.material3
    implementation libs.androidx.activity.compose
    implementation libs.material3.window.size.class1
    androidTestImplementation libs.ui.test.junit4
    androidTestImplementation libs.junit.jupiter
    debugImplementation libs.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest

    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.espresso.device
}