apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace("com.ericmschmidt.latinreader")
    compileSdk(36)
    dataBinding {
        enabled = true
    }
    defaultConfig {
        applicationId("com.ericmschmidt.latinreader")
        minSdkVersion(23)
        targetSdkVersion(36)
        versionCode(15)
        versionName("1.8.0")

    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    //compileOptions {
    //    sourceCompatibility = JavaVersion.VERSION_24 // Or your desired Java version
    //    targetCompatibility = JavaVersion.VERSION_24 // Or your desired Java version
    //}
}

dependencies {
    implementation project(':core')
    implementation project(':views')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.core:core-ktx:1.17.0'
}
