plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace("com.ericmschmidt.latinreader")
    compileSdkVersion(36)
    defaultConfig {
        minSdkVersion(24)
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
        targetSdk 36
    }
    kotlin {
        jvmToolchain {
            languageVersion = JavaLanguageVersion.of("24")
        }
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation project(":views")
    implementation project(":core")
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.compose.foundation)
    implementation(libs.ui)
    implementation(libs.ui.graphics)
    implementation(libs.ui.tooling.preview)
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}
