import com.android.build.api.dsl.AgpTestSuiteInputParameters

plugins {
    alias(libs.plugins.compose.compiler) apply false
    alias libs.plugins.android.application
    alias libs.plugins.jetbrains.kotlin.android
    id "kotlin-kapt"
}

android {
    namespace 'com.ericmschmidt.classicsreader.greek.views'
    compileSdk {
        version = release(36)
    }

    dataBinding {
        enabled = true
    }

    defaultConfig {
        applicationId "com.ericmschmidt.classicsreader.greek.views"
        minSdk 24
        targetSdk 36
        versionCode(3)
        versionName("2.1.0")

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    kotlin {
        jvmToolchain {
            languageVersion = JavaLanguageVersion.of("24")
        }
    }
    testOptions {
        suites {
            adaptiveTest {
                assets {
                }
                targets {
                    'default' {
                    }
                }
                useJunitEngine {
                    inputs AgpTestSuiteInputParameters.TESTED_APKS
                    includeEngines 'journeys-test-engine'
                    enginesDependencies('org.junit.platform:junit-platform-launcher:1.13.4')
                    enginesDependencies('org.junit.platform:junit-platform-engine:1.13.4')
                    enginesDependencies('com.android.tools.journeys:journeys-junit-engine:0.2.1')
                }
                targetVariants 'debug'
            }
        }
    }
}

dependencies {
    implementation project(":core")
    implementation project(":views")
    implementation project(":greekreader")
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}