plugins {
    alias(libs.plugins.compose.compiler)
    alias libs.plugins.android.application
    alias libs.plugins.jetbrains.kotlin.android
}

android {
    namespace 'com.ericmschmidt.classicsreader.greek.compose'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.ericmschmidt.classicsreader.greek.compose"
        minSdk 24
        targetSdk 36
        versionCode(3)
        versionName("2.1.0")

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    kotlin {
        jvmToolchain {
            languageVersion = JavaLanguageVersion.of("24")
        }
    }
}

dependencies {
    implementation project(":core")
    implementation project(":compose")
    implementation project(":greekreader")
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}