buildscript {
    ext.kotlin_version = '2.1.21'
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
    dependencies {
        classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0')
        classpath 'org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.1.21'
        def nav_version = "2.7.7"
        classpath('com.android.tools.build:gradle:8.13.1')
        classpath("androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0")
    }
}

ext {
    kotlin_version = '2.1.21'
    lifecycle_version = '2.7.0'
}

allprojects {
    repositories {
        google()
        maven {
            url = "https://maven.google.com"
        }
        maven {
            url = "https://jitpack.io"
        }
        mavenCentral()
        //here
    }
}

configurations.all {
    resolutionStrategy {
        force("org.jetbrains:annotations:13.0")
    }
}

task clean(type: Delete) {
    delete(rootProject.buildDir)
}
