buildscript {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
    dependencies {
        def nav_version = "2.9.6"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.21"
        classpath('com.android.tools.build:gradle:8.13.2')
        classpath("androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0")
    }
}

ext {
    kotlin_version = "2.1.21"
    lifecycle_version = "2.10.0"
    nav_version = "2.9.6"
    compose_version = "1.12.1"
}

allprojects {
    repositories {
        google()
        maven {
            url = "https://maven.google.com"
        }
        maven {
            url = "https://jitpack.io"
        }
        mavenCentral()
    }
}

configurations.configureEach {
    resolutionStrategy {
        force("org.jetbrains:annotations:13.0")
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
