plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
rootProject.name = "ClassicsReaderAndroid"
include ':core', ':latinreader', ':greekreader'
include ':views'
include ':latinreader-views'
include ':greekreader-views'
include ':compose'
include ':latinreader-compose'
include ':greekreader-compose'
