[versions]
activity-compose = "1.13.0"
adaptive = "1.2.0"
agp = "9.2.0-alpha05"
androidx-ui-tooling = "1.10.6"
appcompat = "1.7.1"
compose-bom = "2026.03.01"
core = "1.7.0"
core-ktx = "1.18.0"
datastore-preferences = "1.2.1"
espresso-core = "3.7.0"
espresso-core-version = "3.0.2"
espresso-device = "1.1.0"
foundation = "1.10.6"
jetbrains-kotlin-android = "2.3.20"
junit = "1.3.0"
junit-version = "4.13.2"
kxml2 = "2.3.0"
legacy-support-v4 = "1.0.0"
lifecycle-runtime-ktx = "2.10.0"
markdownview-android = "2.0.0"
#noinspection GradleDependency
markdownview-android-v1110 = "1.1.1"
material = "1.13.0"
material-ripple = "1.10.6"
mockito-core = "5.23.0"
mockito-kotlin = "6.3.0"
mockk = "1.14.9"
mockk-android = "1.14.9"
navigation-compose = "2.9.7"
navigation-fragment-ktx = "2.9.7"
navigation-safe-args-gradle-plugin = "2.9.7"
navigation-ui-ktx = "2.9.7"
preference-ktx = "1.2.1"
recyclerview = "1.4.0"
robolectric = "4.16.1"
runner = "1.0.2"
truth = "1.4.5"
material3-adaptive-navigation-suite = "1.4.0"
material3-window-size-class1 = "1.4.0"
ui-test-junit4 = "1.10.6"
ui-text-google-fonts = "1.10.6"
junit-jupiter = "6.0.3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
androidx-compose-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }
androidx-compose-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "adaptive" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material-ripple = { module = "androidx.compose.material:material-ripple", version.ref = "material-ripple" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3-adaptive-navigation-suite" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "ui-text-google-fonts" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-espresso-device = { module = "androidx.test.espresso:espresso-device", version.ref = "espresso-device"}
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy-support-v4" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose"}
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
espresso-core = { module = "com.android.support.test.espresso:espresso-core", version.ref = "espresso-core-version" }
junit = { group = "junit", name = "junit", version.ref = "junit-version" }
kxml2 = { module = "net.sf.kxml:kxml2", version.ref = "kxml2" }
#noinspection SimilarGradleDependency
markdownview-android = { module = "com.github.mukeshsolanki:MarkdownView-Android", version.ref = "markdownview-android" }
#noinspection SimilarGradleDependency
markdownview-android-v1 = { module = "com.github.mukeshsolanki:MarkdownView-Android", version.ref =  "markdownview-android-v1110"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk-android" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
runner = { module = "com.android.support.test:runner", version.ref = "runner" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
material3-window-size-class1 = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3-window-size-class1" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "ui-test-junit4" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrains-kotlin-android" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation-safe-args-gradle-plugin" }
kotlin-parcelize = { id = "kotlin-parcelize" }
safeargs = { id = "androidx.navigation.safeargs"}
safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin"}