name: Android CI Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6
      with:
        submodules: 'recursive' # Or 'true' for top-level only

    - name: Set up JDK 24
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '24'

    # Cache Gradle dependencies to speed up subsequent builds
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Make Gradlew Executable
      run: chmod +x ./gradlew

    - name: Run Unit Tests
      run: ./gradlew test

