name: Android CI Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Cache Gradle dependencies to speed up subsequent builds
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make Gradlew Executable
      run: chmod +x ./gradlew

    - name: Run Unit Tests
      run: ./gradlew test

